### PR TITLE
Mac build fix

### LINKED ISSUE #23: None of the macOS apps work
I have tried all three variants on my MacBook Air with M2.

- The ARM version cannot be opened because it is damaged.
- The x64 Intel version closes the window immediately after opening.
- The Brew version cannot be installed because the SHA value does not match.

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**
Seems the executables didn't have `exec` permissions, causing the squeezelite client loading code to throw when trying to get the possible audio output devices. There was also some shenanigans on macOS where using a path other than `bin` for externals was causing it to sometimes fail.

Hopefully fixes #23

### CODE REVIEW

**Comment by arctixdev** [comment]
Hmm dosnt seem to work on linux let me quickly investigate further

**Comment by JeffersonBledsoe** [comment]
> Hmm dosnt seem to work on linux let me quickly investigate further

This could be me changing the `to_str` to `as_str`. I couldn't seem to get it to build without this change on my end. But again, I know nothing about rust so could just have the toolchain setup wrong. I'm using rust 1.76.0.

**Comment by arctixdev** [comment]
Sorry for the long wait! I have been completely off this project for a while. I rewrote some of the rust code now and yeah `to_str` was definetly wrong.

**Review by arctixdev — APPROVED** [review]
Looks fine, sorry for the long wait!

**Comment by ScriptType** [comment]
The [aarch64.dmg](https://github.com/music-assistant/companion/releases/download/v0.0.35/Music.Assistant.Companion_0.0.35_aarch64.dmg)
is still broken, x64 seems to work :/.

**Comment by bbrendon** [comment]
Is there a way to fix it manually? Right now opening says its broken and to move it to the trash.

**Comment by arctixdev** [comment]
Hmm I don't really know... sorry. I have never daily driven MacOS... Does it give any information about what is broken? Does it give you logs or something?

**Comment by angelnu** [comment]
I think it is related to the signature - 

image

It can be circumvented with `sudo xattr -rd com.apple.quarantine /Applications/Music\ Assistant\ Companion.app`

I am not sure if there is a better way that does not require paying 99$/year to to register as Apple developer.

**Comment by arctixdev** [comment]
Actually we just bought a developer account so we just have to set up the signing to get it working then!

**Comment by bbrendon** [comment]
@angelnu That did it!!

**Comment by angelnu** [comment]
it works!

**Pull request merged**
