### PR TITLE
kill squeezelite when closing the app

### LINKED ISSUE #41: Squeezelite not closing when quiting companion
when quiting companion the squeezelite instance stays running so if you had music playing it wont close

so you have to quit using task manager
image

### PR DESCRIPTION
**Pull request by unclejack**
This change modifies the code to keep track of the squeezelite process and to kill it when the app is closed.

The SqueezeLite struct makes it possible to expand this functionality in the future to do other things such as restarting the squeezelite process or implement multiple squeezelite instances.

This change has been tested on Linux.

Fixes #41

### CODE REVIEW

**Comment by arctixdev** [comment]
Awesome thanks a lot! This was much needed. Will test on the different platforms and merge. Might have to wait a day or so as I'm pretty busy at the moment, but I'll try to review and release as quickly as possible 👍

**Review by arctixdev — APPROVED** [review]
LGTM :+1:

**Comment by arctixdev** [comment]
Thanks you for your help!

**Comment by unclejack** [comment]
Sure, I'll send some other PRs in the future.

**Pull request merged**
